# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-27 11:05
from __future__ import unicode_literals

import annoying.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0009_auto_20180512_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='CNSSProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('occupation', models.CharField(blank=True, max_length=511, null=True, verbose_name='Occupation')),
                ('occupational_history', models.TextField(blank=True, null=True, verbose_name='Occupational history')),
                ('member', annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_cnss', to='members.Member')),
            ],
        ),
    ]
